runtime: nodejs20

handlers:
  # URLでルートパスのみ指定された場合に
  # index.html を返すようにマッピングします
  - url: /
    static_files: dist/my-app/browser/index.html
    upload: dist/my-app/browser/index.html
    secure: always

  # URLの正規表現はstatic_dirでは使用でできないので
  # static_filesを使用します
  - url: /(.*)
    static_files: dist/my-app/browser/\1
    upload: dist/my-app/browser/(.*)
    secure: always

  # SSR 用のハンドラを追加
  - url: /api/.*
    script: auto
